### ISSUE TITLE
HI we need COUNTDOWN PLUGIN for Zombie escape 

### ISSUE THREAD

**Issue by Meguzio** [GhostCap-Gaming/Zombie-Escape-Configs-CS-GO#102]
COUNTDOWN FOR MAPS LIKE : ze_aot_trost_v6 ,ze_pirates_port_royal_v5_6
FOR EXAMPLE: >>> GATES WILL BE OPEN ON 20 SEONCDS<<<
CONFIGS /materials are missing for this 2 maps and ofc COUNTDOWN is missing Zombie Escape Mod
![20220517_224757](https://user-images.githubusercontent.com/105892467/169419672-2b9979e9-f561-4b4c-a3c1-613c0774a7a0.jpg)
![Uploading 20220517_224800.jpg…]()

**Comment by Lerrdy** [comment]
This repository does not offer any configs for any countdown plugins.
